# Generated by Django 3.2.4 on 2021-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_data',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nick',
            field=models.CharField(max_length=20),
        ),
    ]
