# Generated by Django 3.2.4 on 2021-07-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210707_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
